-- VirtualBookshelf Database Initial Creation

DROP TABLE IF EXISTS public.websites;
DROP TABLE IF EXISTS public.board_games;
DROP TABLE IF EXISTS public.card_games;
DROP TABLE IF EXISTS public.video_games;
DROP TABLE IF EXISTS public.music;
DROP TABLE IF EXISTS public.tvshows;
DROP TABLE IF EXISTS public.movies;
DROP TABLE IF EXISTS public.books;
DROP TABLE IF EXISTS public.genres;
DROP TABLE IF EXISTS public.categories;
DROP TABLE IF EXISTS public.users;

-- -----------------------------------------------------
-- Create Type
-- -----------------------------------------------------

DROP TYPE IF EXISTS public.book_type;
CREATE TYPE public.book_type AS ENUM
  ('Paper', 'Digital', 'Audiobook', 'Other');


DROP TYPE IF EXISTS public.movie_type;
CREATE TYPE public.movie_type AS ENUM
  ('DVD', 'Blu-Ray', 'Digital', 'VHS', 'Other');


DROP TYPE IF EXISTS public.tvshow_type;
CREATE TYPE public.tvshow_type AS ENUM
  ('DVD', 'Blu-Ray', 'Digital', 'VHS', 'Other');


DROP TYPE IF EXISTS public.music_type;
CREATE TYPE public.music_type AS ENUM
  ('CD', 'Digital', '8-Track', 'Vinyl', 'Other');


DROP TYPE IF EXISTS public.video_game_type;
CREATE TYPE public.video_game_type AS ENUM
  ('Disc', 'Digital', 'External Drive', 'Other');


-- -----------------------------------------------------
-- Table public.users
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
  "user_id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" CHARACTER VARYING NOT NULL,
  "email" CHARACTER VARYING NOT NULL,
  "image" CHARACTER VARYING NOT NULL,
  PRIMARY KEY ("user_id"));


-- -----------------------------------------------------
-- Table public.categories
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categories (
  "category_id" INT NOT NULL,
  "name" CHARACTER VARYING NOT NULL,
  PRIMARY KEY ("category_id"));


-- -----------------------------------------------------
-- Table public.genres
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.genres (
  "genre_id" INT NOT NULL,
  "name" CHARACTER VARYING NOT NULL,
  PRIMARY KEY ("genre_id"));


-- -----------------------------------------------------
-- Table public.books
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.books (
  "book_id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" CHARACTER VARYING NOT NULL,
  "description" CHARACTER VARYING NOT NULL,
  "image" CHARACTER VARYING NOT NULL,
  "author" CHARACTER VARYING NOT NULL,
  "publisher" CHARACTER VARYING NOT NULL,
  "format" book_type NOT NULL,
  "category_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("book_id"),
  CONSTRAINT "fk_books_users"
    FOREIGN KEY ("user_id")
    REFERENCES public.users ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_books_categories1"
    FOREIGN KEY ("category_id")
    REFERENCES public.categories ("category_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table public.movies
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.movies (
  "movie_id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" CHARACTER VARYING NOT NULL,
  "description" CHARACTER VARYING NOT NULL,
  "image" CHARACTER VARYING NOT NULL,
  "director" CHARACTER VARYING NOT NULL,
  "distributor" CHARACTER VARYING NOT NULL,
  "format" movie_type NOT NULL,
  "category_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("movie_id"),
  CONSTRAINT "fk_movies_categories1"
    FOREIGN KEY ("category_id")
    REFERENCES public.categories ("category_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_movies_users1"
    FOREIGN KEY ("user_id")
    REFERENCES public.users ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table public.tvshows
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.tvshows (
  "tvshow_id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" CHARACTER VARYING NOT NULL,
  "description" CHARACTER VARYING NOT NULL,
  "image" CHARACTER VARYING NOT NULL,
  "network" CHARACTER VARYING NOT NULL,
  "format" tvshow_type NOT NULL,
  "category_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("tvshow_id"),
  CONSTRAINT "fk_tvshow_categories1"
    FOREIGN KEY ("category_id")
    REFERENCES public.categories ("category_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_tvshow_users1"
    FOREIGN KEY ("user_id")
    REFERENCES public.users ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table public.video_games
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.video_games (
  "video_game_id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" CHARACTER VARYING NOT NULL,
  "description" CHARACTER VARYING NOT NULL,
  "image" CHARACTER VARYING NOT NULL,
  "developer" CHARACTER VARYING NOT NULL,
  "publisher" CHARACTER VARYING NOT NULL,
  "format" video_game_type NOT NULL,
  "category_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("video_game_id"),
  CONSTRAINT "fk_video_games_categories1"
    FOREIGN KEY ("category_id")
    REFERENCES public.categories ("category_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_video_games_users1"
    FOREIGN KEY ("user_id")
    REFERENCES public.users ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table public.card_games
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.card_games (
  "card_game_id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" CHARACTER VARYING NOT NULL,
  "description" CHARACTER VARYING NOT NULL,
  "image" CHARACTER VARYING NOT NULL,
  "developer" CHARACTER VARYING NOT NULL,
  "publisher" CHARACTER VARYING NOT NULL,
  "category_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("card_game_id"),
  CONSTRAINT "fk_video_games_categories11"
    FOREIGN KEY ("category_id")
    REFERENCES public.categories ("category_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_video_games_users11"
    FOREIGN KEY ("user_id")
    REFERENCES public.users ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table public.board_games
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.board_games (
  "board_game_id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" CHARACTER VARYING NOT NULL,
  "description" CHARACTER VARYING NOT NULL,
  "image" CHARACTER VARYING NOT NULL,
  "developer" CHARACTER VARYING NOT NULL,
  "publisher" CHARACTER VARYING NOT NULL,
  "category_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("board_game_id"),
  CONSTRAINT "fk_video_games_categories12"
    FOREIGN KEY ("category_id")
    REFERENCES public.categories ("category_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_video_games_users12"
    FOREIGN KEY ("user_id")
    REFERENCES public.users ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table public.music
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.music (
  "music_id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" CHARACTER VARYING NOT NULL,
  "description" CHARACTER VARYING NOT NULL,
  "image" CHARACTER VARYING NOT NULL,
  "artist" CHARACTER VARYING NOT NULL,
	"album" CHARACTER VARYING NOT NULL,
  "studio" CHARACTER VARYING NOT NULL,
  "format" music_type NOT NULL,
  "category_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("music_id"),
  CONSTRAINT "fk_music_categories1"
    FOREIGN KEY ("category_id")
    REFERENCES public.categories ("category_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_music_users1"
    FOREIGN KEY ("user_id")
    REFERENCES public.users ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table public.websites
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.websites (
  "website_id" INT NOT NULL,
  "name" CHARACTER VARYING NOT NULL,
  "url" CHARACTER VARYING NOT NULL,
  "description" CHARACTER VARYING NOT NULL,
  "creator" CHARACTER VARYING NOT NULL,
  "image" CHARACTER VARYING NOT NULL,
  "category_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  PRIMARY KEY ("website_id"),
  CONSTRAINT "fk_websites_categories1"
    FOREIGN KEY ("category_id")
    REFERENCES public.categories ("category_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_websites_users1"
    FOREIGN KEY ("user_id")
    REFERENCES public.users ("user_id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

